In [1]:
import pandas as pd
import numpy as np

In [2]:
reviews = pd.read_pickle("concat.p")
lex = pd.read_csv("Trafficking_Lexicon.csv").dropna().rename(columns={'Human Trafficking (weight 0-1-2)':'HT_Weight',
                                                                     "Test Weight (0-1-2)":"Sex_Weight"})
ht_dict = pd.Series(lex.HT_Weight.values, index=lex.TERM).to_dict()
sex_dict = pd.Series(lex.Sex_Weight.values, index=lex.TERM).to_dict()

In [7]:
def lex_score(row):
    HT_total_lexicon_score = 0
    sex_total_lexicon_score = 0
    
    HT_bi_0_count = 0
    HT_bi_1_count = 0
    HT_bi_2_count = 0
    HT_tri_0_count = 0
    HT_tri_1_count = 0
    HT_tri_2_count = 0
    HT_uni_0_count = 0
    HT_uni_1_count = 0
    HT_uni_2_count = 0
    
    sex_bi_0_count = 0
    sex_bi_1_count = 0
    sex_bi_2_count = 0
    sex_tri_0_count = 0
    sex_tri_1_count = 0
    sex_tri_2_count = 0
    sex_uni_0_count = 0
    sex_uni_1_count = 0
    sex_uni_2_count = 0
    
    bi_count = 0
    tri_count = 0
    
    sex_bi_score = 0
    sex_tri_score = 0
    HT_bi_score = 0
    HT_tri_score = 0
    
    prev_any_terms = 0

    prev_sex_0_terms = 0
    prev_sex_1_terms = 0
    prev_sex_2_terms = 0
    
    prev_HT_0_terms = 0
    prev_HT_1_terms = 0
    prev_HT_2_terms = 0
    
    if(pd.notnull(row['review'])):
        for word in row['review']:
            if word in ht_dict.keys():
                HT_total_lexicon_score += ht_dict[word]
                sex_total_lexicon_score += sex_dict[word]
                
                if prev_any_terms == 1:
                    bi_count += 1
                    HT_bi_score += ht_dict[word]
                    sex_bi_score += sex_dict[word]
                    
                elif prev_any_terms > 1:
                    tri_count += 1
                    HT_tri_score += ht_dict[word]
                    sex_tri_score += sex_dict[word]
                    
                prev_any_terms += 1
                
                if ht_dict[word] == 0:
                    HT_uni_0_count += 1
                    
                    if prev_HT_0_terms == 1:
                        HT_bi_0_count += 1
                    elif prev_HT_0_terms > 1:
                        HT_tri_0_count += 1
                    
                    prev_HT_0_terms += 1
                    prev_HT_1_terms = 0
                    prev_HT_2_terms = 0
                    
                elif ht_dict[word] == 1:
                    HT_uni_1_count += 1
                    
                    if prev_HT_1_terms == 1:
                        HT_bi_1_count += 1
                    elif prev_HT_1_terms > 1:
                        HT_tri_1_count += 1
                        
                    prev_HT_1_terms += 1
                    prev_HT_0_terms = 0
                    prev_HT_2_terms = 0
                    
                elif ht_dict[word] == 2:
                    HT_uni_2_count += 1
                    
                    if prev_HT_2_terms == 1:
                        HT_bi_2_count += 1
                    elif prev_HT_2_terms > 1:
                        HT_tri_2_count += 1
                        
                    prev_HT_2_terms += 1
                    prev_HT_0_terms = 0
                    prev_HT_1_terms = 0
                    
                if sex_dict[word] == 0:
                    sex_uni_0_count += 1
                    
                    if prev_sex_0_terms == 1:
                        sex_bi_0_count += 1
                    elif prev_sex_0_terms > 1:
                        sex_tri_0_count += 1
                    
                    prev_sex_0_terms += 1
                    prev_sex_1_terms = 0
                    prev_sex_2_terms = 0
                    
                elif sex_dict[word] == 1:
                    sex_uni_1_count += 1
                    
                    if prev_sex_1_terms == 1:
                        sex_bi_1_count += 1
                    elif prev_sex_1_terms > 1:
                        sex_tri_1_count += 1
                    
                    prev_sex_0_terms = 0
                    prev_sex_1_terms += 1
                    prev_sex_2_terms = 0
                    
                elif sex_dict[word] == 2:
                    sex_uni_2_count += 1
                    
                    if prev_sex_2_terms == 1:
                        sex_bi_2_count += 1
                    elif prev_sex_2_terms > 1:
                        sex_tri_2_count += 1
                    
                    prev_sex_0_terms = 0
                    prev_sex_1_terms = 0
                    prev_sex_2_terms += 1
            else:
                prev_sex_0_terms = 0
                prev_sex_1_terms = 0
                prev_sex_2_terms = 0
                prev_any_terms = 0

                prev_HT_0_terms = 0
                prev_HT_1_terms = 0
                prev_HT_2_terms = 0
    
    row['HT_total_lexicon_score'] = HT_total_lexicon_score
    row['sex_total_lexicon_score'] = sex_total_lexicon_score
    
    row['HT_bi_0_count'] = HT_bi_0_count
    row['HT_bi_1_count'] = HT_bi_1_count
    row['HT_bi_2_count'] = HT_bi_2_count
    row['HT_tri_0_count'] = HT_tri_0_count
    row['HT_tri_1_count'] = HT_tri_1_count
    row['HT_tri_2_count'] = HT_tri_2_count
    row['HT_uni_0_count'] = HT_uni_0_count
    row['HT_uni_1_count'] = HT_uni_1_count
    row['HT_uni_2_count'] = HT_uni_2_count
    
    row['sex_bi_0_count'] = sex_bi_0_count
    row['sex_bi_1_count'] = sex_bi_1_count
    row['sex_bi_2_count'] = sex_bi_2_count
    row['sex_tri_0_count'] = sex_tri_0_count
    row['sex_tri_1_count'] = sex_tri_1_count
    row['sex_tri_2_count'] = sex_tri_2_count
    row['sex_uni_0_count'] = sex_uni_0_count
    row['sex_uni_1_count'] = sex_uni_1_count
    row['sex_uni_2_count'] = sex_uni_2_count
    
    row['bi_count'] = bi_count
    row['tri_count'] = tri_count
    
    row['sex_bi_score'] = sex_bi_score
    row['sex_tri_score'] = sex_tri_score
    row['HT_bi_score'] = HT_bi_score
    row['HT_tri_score'] = HT_tri_score
    return row

In [8]:
sub_reviews = reviews.iloc[:50].copy()
sub_reviews

,name,address,review,lat,lon,yelp,rubmaps,lat_lon
0,A&B,"8000 Sunset Blvd Ste 19 Salon Republic, CA, 90046","I went there twice since my first review,\nOnc...",34.09771,-118.3648,1,0,"(34.09771, -118.3648)"
1,Hollywood Classic Barbershop & Salon,"7268 W Sunset Blvd, CA, 90046",I went in expecting a barber and instead I got...,34.09780,-118.3487,1,0,"(34.0978, -118.3487)"
2,Sola Salon Studios-Nahid professional Hair Sty...,"1218 Irvine Blvd, CA, 92780",Nahid's Hair Salon is surely one of the best h...,33.74603,-117.8089,1,0,"(33.74603, -117.8089)"
3,J Wesley Hair,8000 Sunset Blvd Ste 58 Salon Christopher Coru...,I have nothing but good things to say. I purch...,34.09771,-118.3648,1,0,"(34.09771, -118.3648)"
4,Alexander Braun Hairstylist,"8000 Sunset Blvd studio 65, CA, 90046",NaN,34.09760,-118.3652,1,0,"(34.0976, -118.3652)"
5,Greg Will Cut You Studio,"8000 Sunset Blvd Fl 2, Studio 57 Salon Republi...",I honestly wish I could give Greg 10 stars. Li...,34.09771,-118.3648,1,0,"(34.09771, -118.3648)"
6,Teresa Hill Hair,"8000 Sunset Blvd Ste B 200 Salon Republic, CA,...",I found Teresa on Yelp about 10 years ago and ...,34.09771,-118.3648,1,0,"(34.09771, -118.3648)"
7,D.O.L.L. Ria’s Permanent Cosmetics,"1233 Camino Del Rio S, CA, 92108",Permanent Makeup\nI went to Ria unsure of how ...,32.76482,-117.1524,1,0,"(32.76482, -117.1524)"
8,Anthony Pazos,"8000 Sunset Blvd Ste 39, CA, 90069",I am absolutely in LOVE with how my hair looks...,34.09760,-118.3652,1,0,"(34.0976, -118.3652)"
9,Denessa Sims Hair,"8000 Sunset Blvd Ste 20 Salon Republic, CA, 90069",Denessa is honestly one of the best hairdresse...,34.09771,-118.3648,1,0,"(34.09771, -118.3648)"
10,Gan Southgate Hair Designs,"1815 Adams Ave Halo Hair Studio, CA, 92116",Gan is amazing!!! \nI took my boyfriend to se...,32.76234,-117.1458,1,0,"(32.76234, -117.1458)"
11,Paul Jean Hair Salon,"458 N Robertson Blvd, CA, 90048",He is the best. Fixed my hair after a travesty...,34.07968,-118.3846,1,0,"(34.07968, -118.3846)"
12,Loctician Marie,"8383 Wilshire Blvd Ste 112, CA, 90211",HATERS BEGONE!!!!!!! \n\nI got my locs done he...,34.06510,-118.3734,1,0,"(34.0651, -118.3734)"
13,ML Hair Studio,"8000 Sunset Blvd Ste B200, Rm 69, CA, 90046",Having had some really butchered cuts in my ti...,34.09760,-118.3652,1,0,"(34.0976, -118.3652)"
14,Nianza Style,"8304 Wilshire Blvd, CA, 90211",NaN,34.06377,-118.3723,1,0,"(34.06377, -118.3723)"
15,Yvette Hair Salon,"Salon Republic 8383 Wilshire Blvd, Ste 50,Stud...",I got my brazilian blowout yesterday at this s...,34.06510,-118.3734,1,0,"(34.0651, -118.3734)"
16,Out Look Salon,"7500 W Sunset Blvd, CA, 90046",Go see David Fletcher. \n\nDavid Fletcher is T...,34.09785,-118.3531,1,0,"(34.09785, -118.3531)"
17,Salon Christopher Corum,"8000 Sunset Blvd Ste B-200 Studio 59, CA, 90046",I can't stop looking in the mirror ever since ...,34.09771,-118.3648,1,0,"(34.09771, -118.3648)"
18,Miss Riso,"8000 W Sunset Blvd Studio 1, CA, 90046",Highly recommended! My hair is slowly on the r...,34.09760,-118.3652,1,0,"(34.0976, -118.3652)"
19,Freddy’s Hair Salon,"8630 W 3rd St, CA, 90048",bought a $23 KGB deal for a brazilian wax with...,34.07343,-118.3808,1,0,"(34.07343, -118.3808)"
20,Spa Cieux,"520 Palisades Dr, CA, 90272",This place charged my credit card days before ...,34.04518,-118.5515,1,0,"(34.04518, -118.5515)"
21,Shannon Rae Hair,"8278 Melrose Ave, CA, 90046",Love how natural she made my highlights!! I d...,34.08344,-118.3700,1,0,"(34.08344, -118.37)"
22,Looks of Love Hair Salon,"1217 S La Cienega Blvd, CA, 90035",My son wanted a stylish cut that all the kids ...,34.05519,-118.3765,1,0,"(34.05519, -118.3765)"
23,Shirin Nova Studio,"8000 Sunset Blvd Ste 45, CA, 90046",I've been coming to Shirin Nova for maybe 9 mo...,34.09760,-118.3652,1,0,"(34.0976, -118.3652)"
24,John Vance Hathaway At Salon Republic,"8383 Wilshire Blvd Studio 69, CA, 90211","John is a great stylist, a great person, and b...",34.06510,-118.3734,1,0,"(34.0651, -118.3734)"
25,Jaime Yang Hair Makeup,"8383 Wilshire Blvd Ste 50, CA, 90211","Jaime Yang at Salon Republic (on Pico, Studio ...",34.06510,-118.3734,1,0,"(34.0651, -118.3734)"
26,Teddy Baker Beauty,"8113 W 3rd St, CA, 90048",Where do I even start?! I have spent 5 years i...,34.07240,-118.3664,1,0,"(34.0724, -118.3664)"
27,Elite Makeover,"8383 Wilshire Blvd Ste 50-107, CA, 90211",I have been going to elite makeover have been ...,34.06510,-118.3734,1,0,"(34.0651, -118.3734)"
28,Hair by Ricky Lopez,"8000 Sunset Blvd Fl 2, Ste 40 Salon Republic, ...",I went into Ricky with a groupon for highlight...,34.09771,-118.3648,1,0,"(34.09771, -118.3648)"
29,Peter Bailey Hair,"8000 W Sunset Blvd Ste B 200 , Studio 42, CA, ...",I have been getting my haircut by Peter for ov...,34.09771,-118.3648,1,0,"(34.09771, -118.3648)"
30,Seanara Mode,"265 S Robertson Blvd Ste 4, CA, 90211",What a professional hairstylist and artist! I ...,34.06308,-118.3839,1,0,"(34.06308, -118.3839)"
31,Jin Bang Hair,"8383 Wilshire Blvd Ste 50 Unit 92, CA, 90211",I just saw Jin for the first time and I am soo...,34.06510,-118.3734,1,0,"(34.0651, -118.3734)"
32,Ana Nelson Hair Stylist,"1014 Pearl St Salon Envie, CA, 92037",I have two words for you... ANA NELSON ...hair...,32.84077,-117.2720,1,0,"(32.84077, -117.272)"
33,Salon Society,"7655 Girard Ave Ste 118, CA, 92037",I wanted to to try a new hair salon today so I...,32.84321,-117.2732,1,0,"(32.84321, -117.2732)"
34,Lovely Beauty Salon,"35149 Newark Blvd, CA, 94560",I came in to see Virgie to do a light ombre wi...,37.54845,-122.0476,1,0,"(37.54845, -122.0476)"
35,Imagine Hair & Beauty,"46288 Warm Spring Blvd, CA, 94539",I was back in town and ended up in shopping pl...,37.49279,-121.9303,1,0,"(37.49279, -121.9303)"
36,Beauty Plus Salon,"3170 Santa Rita Rd Ste A-3, CA, 94566",I move to plesanton 2 years back and was looki...,37.69133,-121.8770,1,0,"(37.69133, -121.877)"
37,Braids by Lydiaa,"300 E 4th St Ste 112, CA, 90802","Her work, and her work ethic is everything!\nW...",33.77134,-118.1888,1,0,"(33.77134, -118.1888)"
38,ABC Nails,"10620 W Pico Blvd, CA, 90064",My brakes were crapping out on me and I had to...,34.04294,-118.4226,1,0,"(34.04294, -118.4226)"
39,InStyle Nails & Spa,"8619 Santa Monica Blvd, CA, 90069",Kelly and Joana are amazing. They are incredib...,34.08787,-118.3797,1,0,"(34.08787, -118.3797)"
40,Kris Gagnon Hair,"3931 18th St, CA, 94114","I was driving home, planning to stop in the Pa...",37.76103,-122.4313,1,0,"(37.76103, -122.4313)"
41,Nails by Design & Spa,"8961 W Sunset Blvd Ste 1A, CA, 90069",Annie did my acrylic extensions with SNS dippi...,34.09085,-118.3870,1,0,"(34.09085, -118.387)"
42,Roger Ervin,"3852 3rd Ave Thick Salon, CA, 92103","I've been going to Roger for years for ""blow-o...",32.74790,-117.1629,1,0,"(32.7479, -117.1629)"
43,Beverly Hills Laser Institute,"8920 Wilshire Blvd Ste404, CA, 90211",NaN,34.06686,-118.3864,1,0,"(34.06686, -118.3864)"
44,Hair For All Seasons,"121 University Ave, CA, 92103",I had a fantastic haircut from Kathy... It was...,32.74819,-117.1641,1,0,"(32.74819, -117.1641)"
45,Junryl Molina - JVM Collections,"9725 S Santa Monica Blvd, CA, 90210",Junryl is hands down one of the most talented ...,34.06832,-118.4080,1,0,"(34.06832, -118.408)"
46,Hair by Erin Ditlow,"3594 5th Ave Jean Claude Salon, CA, 92103",Erin is fantastic!!! Not only did she squeeze ...,32.74315,-117.1605,1,0,"(32.74315, -117.1605)"
47,Great Clips,"15992 Los Gatos Blvd, CA, 95032",I have had good results every time. I always u...,37.23586,-121.9615,1,0,"(37.23586, -121.9615)"
48,Dash Exchange,"8383 Wilshire Blvd Studio 60, CA, 90210",In high school I had the same stylist for year...,34.06510,-118.3734,1,0,"(34.0651, -118.3734)"
49,454 North Salon,"454 N Robertson Blvd, CA, 90048",Wonderful hair salon. Karen does excellent col...,34.07963,-118.3844,1,0,"(34.07963, -118.3844)"

In [9]:
sub_reviews = sub_reviews.apply(lex_score, axis=1)

,name,address,review,lat,lon,yelp,rubmaps,lat_lon,HT_total_lexicon_score,sex_total_lexicon_score,...,sex_tri_2_count,sex_uni_0_count,sex_uni_1_count,sex_uni_2_count,bi_count,tri_count,sex_bi_score,sex_tri_score,HT_bi_score,HT_tri_score
6,Teresa Hill Hair,"8000 Sunset Blvd Ste B 200 Salon Republic, CA,...",I found Teresa on Yelp about 10 years ago and ...,34.09771,-118.3648,1,0,"(34.09771, -118.3648)",0,24.0,...,0,6,0,12,1,1,0.0,0.0,0,0
12,Loctician Marie,"8383 Wilshire Blvd Ste 112, CA, 90211",HATERS BEGONE!!!!!!! \n\nI got my locs done he...,34.06510,-118.3734,1,0,"(34.0651, -118.3734)",0,22.0,...,0,16,0,11,1,1,0.0,0.0,0,0
13,ML Hair Studio,"8000 Sunset Blvd Ste B200, Rm 69, CA, 90046",Having had some really butchered cuts in my ti...,34.09760,-118.3652,1,0,"(34.0976, -118.3652)",0,4.0,...,0,4,0,2,1,1,0.0,0.0,0,0
39,InStyle Nails & Spa,"8619 Santa Monica Blvd, CA, 90069",Kelly and Joana are amazing. They are incredib...,34.08787,-118.3797,1,0,"(34.08787, -118.3797)",0,14.0,...,0,8,0,7,1,1,0.0,0.0,0,0
44,Hair For All Seasons,"121 University Ave, CA, 92103",I had a fantastic haircut from Kathy... It was...,32.74819,-117.1641,1,0,"(32.74819, -117.1641)",0,24.0,...,1,3,0,12,1,1,2.0,2.0,0,0

In [11]:
sub_reviews[sub_reviews['tri_count'] > 0]

,name,address,review,lat,lon,yelp,rubmaps,lat_lon,HT_total_lexicon_score,sex_total_lexicon_score,HT_bi_0_count,HT_bi_1_count,HT_bi_2_count,HT_tri_0_count,HT_tri_1_count,HT_tri_2_count,HT_uni_0_count,HT_uni_1_count,HT_uni_2_count,sex_bi_0_count,sex_bi_1_count,sex_bi_2_count,sex_tri_0_count,sex_tri_1_count,sex_tri_2_count,sex_uni_0_count,sex_uni_1_count,sex_uni_2_count,bi_count,tri_count,sex_bi_score,sex_tri_score,HT_bi_score,HT_tri_score
6,Teresa Hill Hair,"8000 Sunset Blvd Ste B 200 Salon Republic, CA,...",I found Teresa on Yelp about 10 years ago and ...,34.09771,-118.3648,1,0,"(34.09771, -118.3648)",0,24.0,1,0,0,1,0,0,18,0,0,1,0,0,1,0,0,6,0,12,1,1,0.0,0.0,0,0
12,Loctician Marie,"8383 Wilshire Blvd Ste 112, CA, 90211",HATERS BEGONE!!!!!!! \n\nI got my locs done he...,34.06510,-118.3734,1,0,"(34.0651, -118.3734)",0,22.0,1,0,0,1,0,0,27,0,0,1,0,0,1,0,0,16,0,11,1,1,0.0,0.0,0,0
13,ML Hair Studio,"8000 Sunset Blvd Ste B200, Rm 69, CA, 90046",Having had some really butchered cuts in my ti...,34.09760,-118.3652,1,0,"(34.0976, -118.3652)",0,4.0,1,0,0,1,0,0,6,0,0,1,0,0,1,0,0,4,0,2,1,1,0.0,0.0,0,0
39,InStyle Nails & Spa,"8619 Santa Monica Blvd, CA, 90069",Kelly and Joana are amazing. They are incredib...,34.08787,-118.3797,1,0,"(34.08787, -118.3797)",0,14.0,1,0,0,1,0,0,15,0,0,1,0,0,1,0,0,8,0,7,1,1,0.0,0.0,0,0
44,Hair For All Seasons,"121 University Ave, CA, 92103",I had a fantastic haircut from Kathy... It was...,32.74819,-117.1641,1,0,"(32.74819, -117.1641)",0,24.0,1,0,0,1,0,0,15,0,0,0,0,1,0,0,1,3,0,12,1,1,2.0,2.0,0,0

In [10]:
pd.set_option('max_columns',None)